# Generated by Django 6.0.1 on 2026-02-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actionneur',
            fields=[
                ('id_actionneur', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('etat_actuel', models.CharField(max_length=20)),
                ('puissance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_installation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id_capteur', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('date_installation', models.DateField()),
                ('etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Serre',
            fields=[
                ('id_serre', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=100)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type_culture', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_declenchement', models.DateField()),
                ('heure_declenchement', models.TimeField()),
                ('statut', models.CharField(max_length=20)),
                ('actionneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='firstapp.actionneur')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id_mesure', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_mesuree', models.DecimalField(decimal_places=4, max_digits=8)),
                ('unite_mesure', models.CharField(max_length=10)),
                ('horodatage', models.DateTimeField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='firstapp.capteur')),
            ],
        ),
        migrations.CreateModel(
            name='RegleAutomatisation',
            fields=[
                ('id_regle', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('condition_declenchement', models.CharField(max_length=200)),
                ('statut_activation', models.CharField(max_length=20)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='firstapp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id_plante', models.AutoField(primary_key=True, serialize=False)),
                ('espece', models.CharField(max_length=50)),
                ('variete', models.CharField(max_length=50)),
                ('stade_croissance', models.CharField(max_length=30)),
                ('date_plantation', models.DateField()),
                ('densite_plantation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('serre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to='firstapp.serre')),
            ],
        ),
        migrations.AddField(
            model_name='capteur',
            name='serre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='firstapp.serre'),
        ),
        migrations.AddField(
            model_name='actionneur',
            name='serre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionneurs', to='firstapp.serre'),
        ),
    ]
