# Generated by Django 6.0.1 on 2026-02-07 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regleautomatisation',
            name='commande',
        ),
        migrations.AddField(
            model_name='commande',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='firstapp.regleautomatisation'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='horodatage',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
