# Generated by Django 6.0.1 on 2026-02-09 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_regleautomatisation_commande_commande_regle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
