# Generated by Django 6.0.1 on 2026-02-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_commande_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='regleautomatisation',
            name='action',
            field=models.CharField(default='on', max_length=30),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='actionneur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.actionneur'),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='duree_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='serre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.serre'),
        ),
    ]
