# Generated by Django 6.0.1 on 2026-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_regleautomatisation_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionneur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mesure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
